### ISSUE TITLE
Show PHP Transformations error in 3.0

### ISSUE THREAD

**Issue by jakebathman** [akalongman/sublimetext-codeformatter#174]
When using the command palette item "CodeFormatter: Show PHP Transformations", nothing happens. In the console, the following error is shown:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "C:\Users\{username}\AppData\Roaming\Sublime Text 3\Packages\CodeFormatter\CodeFormatter.py", line 140, in run
    show_error("Formatter error:\n"+stderr.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

For anyone looking for a list in the meantime, see this as a reference: https://github.com/phpfmt/sublime-phpfmt/blob/master/README.md

**Comment by akalongman** [comment]
Try 3.0.1 version

**Comment by jakebathman** [comment]
Looks good, thanks man.
