### ISSUE TITLE
Unable to format SCSS in ST3

### ISSUE THREAD

**Issue by aaronsummers** [akalongman/sublimetext-codeformatter#200]
When I try to format any SCSS I recieve this error.

**Format error;
Formatting python files on ST3 not supported.**

Anyone have an idea about a fix for this?

**Comment by akalongman** [comment]
Which syntax is set in Sublime Text when you opening SCSS files?

**Comment by aaronsummers** [comment]
SASS

**Comment by akalongman** [comment]
Can you show full window screenshot when SCSS file is open?

**Comment by aaronsummers** [comment]
![screen shot 2016-03-07 at 12 56 01](https://cloud.githubusercontent.com/assets/5161396/13570084/006887d0-e464-11e5-9429-7273a3b61ee9.png)

**Comment by akalongman** [comment]
Can you also show me your CodeFormatter settings?

**Comment by aaronsummers** [comment]
<img width="641" alt="screen shot 2016-03-07 at 12 58 24" src="https://cloud.githubusercontent.com/assets/5161396/13570139/536ce426-e464-11e5-8c6d-451d8481da14.png">

**Comment by akalongman** [comment]
Try add sass in syntaxes under scss_options like:
```
"codeformatter_scss_options":
{
    "syntaxes": "scss, sass",
    ...
```

**Comment by aaronsummers** [comment]
Updated and restarted but unfortunatly i'm still receiving the same error message.

Works perfectly with every other syntax.

**Comment by akalongman** [comment]
Strange error. Which packages you have installed?

**Comment by aaronsummers** [comment]
1. Color Highlighter
2. Markdown Editing
3. Package Control
4. Package Syncing
5. CodeFormatter
6. Emmet
7. Sidebar Enhancements
8. Autoprefixer

**Comment by aaronsummers** [comment]
Oh and sass-textmate-bundle

**Comment by emps** [comment]
here same problem any fix coming ?

**Comment by ashramwen** [comment]
I have the same problem.
#191

**Comment by rongl** [comment]
I have the same problem.

**Comment by bcreeves** [comment]
Disabling the CSS3 package (https://packagecontrol.io/packages/CSS3) fixed this issue for me.

**Comment by jfcartier** [comment]
Disabling css3 package didnt work for me.
Here is the error i got on the console  : 

```
PARSING SAVED VIEW
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 480, in on_post_save_async
    callback.on_post_save_async(v)
  File "css_style_completions in /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 69, in on_post_save_async
  File "style_parser in /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 132, in parse_view
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 986: ordinal not in range(128)
```

**Comment by ali-n4i** [comment]
I have the same problem.

**Comment by aqianchu** [comment]
Is there anyone has fix it ? How to do?

**Comment by Forgo7ten** [comment]
oh, I have the same problem.
