### ISSUE TITLE
problem format javascript

### ISSUE THREAD

**Issue by ElRochito** [akalongman/sublimetext-codeformatter#203]
Hi,

I got this error when I try to format javascript file

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./CodeFormatter.py", line 95, in run
  File "./codeformatter/formatter.py", line 116, in format
    if self.have_label or not self.hard_break:
  File "./codeformatter/formatter.py", line 149, in clean
    s = chr(ord(case) + x)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 22799: ordinal not in range(128
```

I've got the latest version of this plugin.

Someone has got this problem ?

Thanks

**Comment by whitnelson** [comment]
Yup, getting the same error. Can't figure it out.
