### ISSUE TITLE
Format error: [Errno 32] Broken pipe error: CodeFormatter

### ISSUE THREAD

**Issue by myalban** [akalongman/sublimetext-codeformatter#32]
I got this when I try to format a PHP script 

Format error:
[Errno 32] Broken pipe
error: CodeFormatter

My system is win 7 64 bits and sublime text 2

And with another file I got this :    

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\code_formatter.py", line 60, in run
  File ".\codeformatter\formatter.py", line 62, in format
  File ".\codeformatter\formatter.py", line 83, in clean
  File ".\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 96: unexpected code byte

**Comment by jayelkaake** [comment]
Getting same error.

**Comment by cassini-mohsin** [comment]
i just installed php on my windows.
and provided path.
"codeformatter_php_path": "C:/php/php.exe",

and it works for me then.
